name: Add Random Quote to Profile

on:
  # Trigger on push to main branch
  push:
    branches:
      - main

  # Trigger on every hour (using cron schedule)
  schedule:
    - cron: '0 * * * *'  

  # Allow manual trigger of the workflow
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install necessary dependencies (Python is optional here, just used for scripting if needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Add random quote to profile and remove previous quote
      - name: Add random quote to profile
        run: |
          # Fetch a random line from quotes.txt
          RANDOM_QUOTE=$(shuf -n 1 quotes.txt)

          # Check if the "Random quote of the hour" section exists and remove it if it does
          if grep -q "## Random quote of the hour" README.md; then
            # Remove the previous quote section
            sed -i '/## Random quote of the hour/,/^$/d' README.md
          fi

          # Append the new random quote with heading to the end of README.md
          echo -e "\n## Random quote of the hour\n> $RANDOM_QUOTE\n" >> README.md

          # Commit and push the change to the repository
          git config --global user.name "Ben Bell's Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Add random quote of the hour"
          git push origin main
